spring:
  profiles:
    active: mysql

---
spring:
  config:
    activate:
      on-profile: h2

  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

---
spring:
  config:
    activate:
      on-profile: mysql
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/batch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rla363636!

  batch:
    jdbc:
      initialize-schema: always # JPA Auto ddl 과 유사하게 내부 배치 테이블 스크립트 동작 설정
    job:
      enabled: false # 스프링 실행 시, 빈으로 등록된 배치 실행 여부 설정


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE